export const GET_EVENTS_PENDING = 'GET_EVENTS_PENDING';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';
export const SAVE_EVENTS = 'SAVE_EVENTS';

export const ADD_EVENT_MODAL = 'ADD_EVENT_MODAL';
export const ADD_EVENT_CLOSE = 'ADD_EVENT_CLOSE';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const ADD_TOKEN = 'ADD_TOKEN';

export const ADD_EVENT_PENDING = 'ADD_EVENT_PENDING';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_ERROR = 'ADD_EVENT_ERROR';

export const GET_USERS_PENDING = 'GET_USERS_PENDING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const GET_ME = 'GET_ME';

export const HAS_DISPATCHED = 'HAS_DISPATCHED';

export const DELETE_EVENT_PENDING = 'DELETE_EVENT_PENDING';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR';
export const SELECT_EVENT = 'SELECT_EVENT';
export const UPDATE_EVENT_PENDING = 'UPDATE_EVENT_PENDING';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_ERROR = 'UPDATE_EVENT_ERROR';
export const ACCEPT_DECLINE_EVENT_PENDING = 'ACCEPT_DECLINE_EVENT_PENDING';
export const ACCEPT_DECLINE_EVENT_SUCCESS = 'ACCEPT_DECLINE_EVENT_SUCCESS';
export const ACCEPT_DECLINE_EVENT_ERROR = 'ACCEPT_DECLINE_EVENT_ERROR';

export const GET_PENDING_EVENTS_PENDING = 'GET_PENDING_EVENTS';
export const GET_PENDING_EVENTS_SUCCESS = 'GET_PENDING_EVENTS_SUCCESS';
export const GET_PENDING_EVENTS_ERROR = 'GET_PENDING_EVENTS_ERROR';
export const UPDATE_PAGE_TITLE = 'UPDATE_PAGE_TITLE';
export const GET_MY_SCHOOL_PENDING = 'GET_MY_SCHOOL_PENDING';
export const GET_MY_SCHOOL_SUCCESS = 'GET_MY_SCHOOL_SUCCESS';
export const GET_MY_SCHOOL_ERROR = 'GET_MY_SCHOOL_ERROR';
export const GET_EVENTS_REPARTITION_PENDING = 'GET_EVENTS_REPARTITION_PENDING';
export const GET_EVENTS_REPARTITION_SUCCESS = 'GET_EVENTS_REPARTITION_SUCCESS';
export const GET_EVENTS_REPARTITION_ERROR = 'GET_EVENTS_REPARTITION_ERROR';
